/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/{year}": {
    /** Gets all accident details for accidents occuring in the specified year */
    get: operations["AccidentStats_Get"];
  };
}

export interface components {
  schemas: {
    "Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray": components["schemas"]["Tfl.Api.Presentation.Entities.AccidentStats.AccidentDetail"][];
    "Tfl.Api.Presentation.Entities.AccidentStats.AccidentDetail": {
      /** Format: int32 */
      id: number;
      /** Format: double */
      lat: number;
      /** Format: double */
      lon: number;
      location: string;
      /** Format: date-time */
      date: string;
      severity: string;
      borough: string;
      casualties: components["schemas"]["Tfl.Api.Presentation.Entities.AccidentStats.Casualty"][];
      vehicles: components["schemas"]["Tfl.Api.Presentation.Entities.AccidentStats.Vehicle"][];
    };
    "Tfl.Api.Presentation.Entities.AccidentStats.Casualty": {
      /** Format: int32 */
      age: number;
      class: string;
      severity: string;
      mode: string;
      ageBand: string;
    };
    "Tfl.Api.Presentation.Entities.AccidentStats.Vehicle": {
      type: string;
    };
    "Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray-1": components["schemas"]["Tfl.Api.Presentation.Entities.AccidentStats.AccidentDetail"][];
    "Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray-2": components["schemas"]["Tfl.Api.Presentation.Entities.AccidentStats.AccidentDetail"][];
    "Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray-3": components["schemas"]["Tfl.Api.Presentation.Entities.AccidentStats.AccidentDetail"][];
  };
}

export interface operations {
  /** Gets all accident details for accidents occuring in the specified year */
  AccidentStats_Get: {
    parameters: {
      path: {
        /** Format - int32. The year for which to filter the accidents on. */
        year: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray"];
          "text/json": components["schemas"]["Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray-1"];
          "application/xml": components["schemas"]["Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray-2"];
          "text/xml": components["schemas"]["Tfl-Api-Presentation-Entities-AccidentStats-AccidentDetailArray-3"];
        };
      };
    };
  };
}

export interface external {}
