/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/{Naptan}": {
    /** Returns crowding information for Naptan */
    get: operations["naptan"];
  };
  "/{Naptan}/{DayOfWeek}": {
    /** Returns crowding information for Naptan for Day of Week */
    get: operations["dayofweek"];
  };
  "/{Naptan}/Live": {
    /** Returns live crowding information for Naptan */
    get: operations["live"];
  };
}

export interface components {}

export interface operations {
  /** Returns crowding information for Naptan */
  naptan: {
    parameters: {
      path: {
        /** Naptan code */
        Naptan: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  /** Returns crowding information for Naptan for Day of Week */
  dayofweek: {
    parameters: {
      path: {
        /** Naptan code */
        Naptan: string;
        /** Day of week */
        DayOfWeek: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  /** Returns live crowding information for Naptan */
  live: {
    parameters: {
      path: {
        /** Naptan code */
        Naptan: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
}

export interface external {}
