/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    /** List of all currently disrupted lift routes */
    get: operations["get"];
  };
}

export interface components {
  schemas: {
    LiftDisruption: {
      /** @description Ics code for the disrupted lift route */
      icsCode: string;
      /** @description Naptan code for the stop area of the disrupted lift route */
      naptanCode: string;
      /** @description Name of the stop point of the disrupted lift route */
      stopPointName: string;
      /** @description Id for the start of the disrupted lift route */
      outageStartArea: string;
      /** @description Id for the end of the disrupted lift route */
      outageEndArea: string;
      /** @description Customer facing message for the disrupted lift route */
      message: string;
    };
    Get200ApplicationJsonResponse: components["schemas"]["LiftDisruption"][];
  };
}

export interface operations {
  /** List of all currently disrupted lift routes */
  get: {
    responses: {
      /** Expected response */
      200: {
        content: {
          "application/json": components["schemas"]["Get200ApplicationJsonResponse"];
        };
      };
    };
  };
}

export interface external {}
