/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    /** Search the site for occurrences of the query string. The maximum number of results returned is equal to the maximum page size of 100. To return subsequent pages, use the paginated overload. */
    get: operations["Search_GetByQueryQuery"];
  };
  "/BusSchedules": {
    /** Searches the bus schedules folder on S3 for a given bus number. */
    get: operations["Search_BusSchedulesByQueryQuery"];
  };
  "/Meta/SearchProviders": {
    /** Gets the available searchProvider names. */
    get: operations["Search_MetaSearchProviders"];
  };
  "/Meta/Categories": {
    /** Gets the available search categories. */
    get: operations["Search_MetaCategories"];
  };
  "/Meta/Sorts": {
    /** Gets the available sorting options. */
    get: operations["Search_MetaSorts"];
  };
}

export interface components {
  schemas: {
    Tfl: {
      id: string;
      url: string;
      name: string;
      /** Format: double */
      lat: number;
      /** Format: double */
      lon: number;
    };
    "Tfl-2": {
      query: string;
      /** Format: int32 */
      from: number;
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      provider: string;
      /** Format: int32 */
      total: number;
      matches: components["schemas"]["Tfl"][];
      /** Format: double */
      maxScore: number;
    };
    MetaSearchProvidersGet200ApplicationJsonResponse: string[];
    MetaSearchProvidersGet200TextJsonResponse: string[];
    MetaSearchProvidersGet200ApplicationXmlResponse: string[];
    MetaSearchProvidersGet200TextXmlResponse: string[];
    MetaCategoriesGet200ApplicationJsonResponse: string[];
    MetaCategoriesGet200TextJsonResponse: string[];
    MetaCategoriesGet200ApplicationXmlResponse: string[];
    MetaCategoriesGet200TextXmlResponse: string[];
    MetaSortsGet200ApplicationJsonResponse: string[];
    MetaSortsGet200TextJsonResponse: string[];
    MetaSortsGet200ApplicationXmlResponse: string[];
    MetaSortsGet200TextXmlResponse: string[];
  };
}

export interface operations {
  /** Search the site for occurrences of the query string. The maximum number of results returned is equal to the maximum page size of 100. To return subsequent pages, use the paginated overload. */
  Search_GetByQueryQuery: {
    parameters: {
      query: {
        /** The search query */
        query: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-2"];
          "text/json": components["schemas"]["Tfl-2"];
          "application/xml": components["schemas"]["Tfl-2"];
          "text/xml": components["schemas"]["Tfl-2"];
        };
      };
    };
  };
  /** Searches the bus schedules folder on S3 for a given bus number. */
  Search_BusSchedulesByQueryQuery: {
    parameters: {
      query: {
        /** The search query */
        query: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-2"];
          "text/json": components["schemas"]["Tfl-2"];
          "application/xml": components["schemas"]["Tfl-2"];
          "text/xml": components["schemas"]["Tfl-2"];
        };
      };
    };
  };
  /** Gets the available searchProvider names. */
  Search_MetaSearchProviders: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MetaSearchProvidersGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["MetaSearchProvidersGet200TextJsonResponse"];
          "application/xml": components["schemas"]["MetaSearchProvidersGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["MetaSearchProvidersGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the available search categories. */
  Search_MetaCategories: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MetaCategoriesGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["MetaCategoriesGet200TextJsonResponse"];
          "application/xml": components["schemas"]["MetaCategoriesGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["MetaCategoriesGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the available sorting options. */
  Search_MetaSorts: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MetaSortsGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["MetaSortsGet200TextJsonResponse"];
          "application/xml": components["schemas"]["MetaSortsGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["MetaSortsGet200TextXmlResponse"];
        };
      };
    };
  };
}

export interface external {}
