/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/{ids}/Arrivals": {
    /** Gets the predictions for a given list of vehicle Id's. */
    get: operations["Vehicle_GetByPathIds"];
  };
  "/EmissionSurcharge": {
    /** Gets the Emissions Surcharge compliance for the Vehicle */
    get: operations["Vehicle_GetEmissionsSurchargeComplianceByQueryVrm"];
  };
  "/UlezCompliance": {
    /** Gets the Ulez Surcharge compliance for the Vehicle */
    get: operations["Vehicle_GetUlezComplianceByQueryVrm"];
  };
}

export interface components {
  schemas: {
    Tfl: {
      countdownServerAdjustment: string;
      /** Format: date-time */
      source: string;
      /** Format: date-time */
      insert: string;
      /** Format: date-time */
      read: string;
      /** Format: date-time */
      sent: string;
      /** Format: date-time */
      received: string;
    };
    /** @description DTO to capture the prediction details */
    "Tfl-2": {
      /** @description The identitier for the prediction */
      id: string;
      /**
       * Format: int32
       * @description The type of the operation (1: is new or has been updated, 2: should be deleted from any client cache)
       */
      operationType: number;
      /** @description The actual vehicle in transit (for train modes, the leading car of the rolling set) */
      vehicleId: string;
      /** @description Identifier for the prediction */
      naptanId: string;
      /** @description Station name */
      stationName: string;
      /** @description Unique identifier for the Line */
      lineId: string;
      /** @description Line Name */
      lineName: string;
      /** @description Platform name (for bus, this is the stop letter) */
      platformName: string;
      /** @description Direction (unified to inbound/outbound) */
      direction: string;
      /** @description Bearing (between 0 to 359) */
      bearing: string;
      /** @description Naptan Identifier for the prediction's destination */
      destinationNaptanId: string;
      /** @description Name of the destination */
      destinationName: string;
      /**
       * Format: date-time
       * @description Timestamp for when the prediction was inserted/modified (source column drives what objects are broadcast on each iteration)
       */
      timestamp: string;
      /**
       * Format: int32
       * @description Prediction of the Time to station in seconds
       */
      timeToStation: number;
      /** @description The current location of the vehicle. */
      currentLocation: string;
      /** @description Routing information or other descriptive text about the path of the vehicle towards the destination */
      towards: string;
      /**
       * Format: date-time
       * @description The expected arrival time of the vehicle at the stop/station
       */
      expectedArrival: string;
      /**
       * Format: date-time
       * @description The expiry time for the prediction
       */
      timeToLive: string;
      /** @description The mode name of the station/line the prediction relates to */
      modeName: string;
      timing: components["schemas"]["Tfl"];
    };
    "Tfl-3": {
      vrm: string;
      type: string;
      make: string;
      model: string;
      colour: string;
      /** @enum {string} */
      compliance: "NotAvailable" | "NotCompliant" | "Compliant" | "Exempt";
    };
    "ids-ArrivalsGet200ApplicationJsonResponse": components["schemas"]["Tfl-2"][];
    "ids-ArrivalsGet200TextJsonResponse": components["schemas"]["Tfl-2"][];
    "ids-ArrivalsGet200ApplicationXmlResponse": components["schemas"]["Tfl-2"][];
    "ids-ArrivalsGet200TextXmlResponse": components["schemas"]["Tfl-2"][];
  };
}

export interface operations {
  /** Gets the predictions for a given list of vehicle Id's. */
  Vehicle_GetByPathIds: {
    parameters: {
      path: {
        /** A comma-separated list of vehicle ids e.g. LX58CFV,LX11AZB,LX58CFE. Max approx. 25 ids. */
        ids: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ids-ArrivalsGet200ApplicationJsonResponse"];
          "text/json": components["schemas"]["ids-ArrivalsGet200TextJsonResponse"];
          "application/xml": components["schemas"]["ids-ArrivalsGet200ApplicationXmlResponse"];
          "text/xml": components["schemas"]["ids-ArrivalsGet200TextXmlResponse"];
        };
      };
    };
  };
  /** Gets the Emissions Surcharge compliance for the Vehicle */
  Vehicle_GetEmissionsSurchargeComplianceByQueryVrm: {
    parameters: {
      query: {
        /** The Vehicle Registration Mark */
        vrm: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-3"];
          "text/json": components["schemas"]["Tfl-3"];
          "application/xml": components["schemas"]["Tfl-3"];
          "text/xml": components["schemas"]["Tfl-3"];
        };
      };
    };
  };
  /** Gets the Ulez Surcharge compliance for the Vehicle */
  Vehicle_GetUlezComplianceByQueryVrm: {
    parameters: {
      query: {
        /** The Vehicle Registration Mark */
        vrm: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tfl-3"];
          "text/json": components["schemas"]["Tfl-3"];
          "application/xml": components["schemas"]["Tfl-3"];
          "text/xml": components["schemas"]["Tfl-3"];
        };
      };
    };
  };
}

export interface external {}
